version: '3.7'

services:

  tarefas:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - 5001:5000
    environment:
      - FLASK_APP=sistema/__init__.py
      - FLASK_ENV=development