version: '3.7'

services:

  tarefas:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ['/usr/src/app/entrypoint.sh']
    volumes:
      - .:/usr/src/app
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=sistema.config.DevelopmentConfig
      - DATABASE_DEV_URL=postgresql://postgres:postgres@tarefas-db:5432/tarefas_dev
    depends_on:
      - tarefas-db

  tarefas-db:
    build:
      context: ./db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres